[project]
name = "ldparser"
version = "0.1.0"
description = "Parser for MoTec ld files. Code created through reverse engineering the data format."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "pandas>=2.3.0",
]
